name: movies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2 
  core: 
    path: ../core
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.4
flutter:

 