// Mocks generated by Mockito 5.0.16 from annotations
// in tv_series/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:core/tv_series/domain/entities/tv.dart' as _i6;
import 'package:core/tv_series/domain/entities/tv_detail.dart' as _i7;
import 'package:core/tv_series/domain/entities/tv_episode.dart' as _i8;
import 'package:core/tv_series/domain/repositories/tv_repository.dart' as _i3;
import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i3.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getTvAiringToday() =>
      (super.noSuchMethod(Invocation.method(#getTvAiringToday, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getPopularTVs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTVs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getTopRatedTVs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTVs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>> getDetailTVs(int? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailTVs, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i7.TvDetail>>.value(
                  _FakeEither_0<_i5.Failure, _i7.TvDetail>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.TvDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvEpisode>>> getTvSeasonEpisodes(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeasonEpisodes, [id, seasonNumber]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i8.TvEpisode>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i8.TvEpisode>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvEpisode>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> searchTVs(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTVs, [query]),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistTv(
          _i7.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlistTv(
          _i7.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isTvAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isTvAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>> getWatchlistTVs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTVs, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Tv>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Tv>>>);
  @override
  String toString() => super.toString();
}
